# Generated by Django 4.1.1 on 2023-11-05 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('prefix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BowlerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('prefix', models.CharField(max_length=250)),
                ('groupId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('middleName', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lastName', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nickName', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.IntegerField(blank=True, default=None, null=True)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
                ('weight', models.FloatField(blank=True, default=None, null=True)),
                ('batting', models.BooleanField(blank=True, default=None, null=True)),
                ('bowling', models.BooleanField(blank=True, default=None, null=True)),
                ('wicketKeeper', models.BooleanField(blank=True, default=None, null=True)),
                ('fielding', models.BooleanField(blank=True, default=None, null=True)),
                ('playerImage', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('pace', models.BooleanField(blank=True, default=None, null=True)),
                ('spin', models.BooleanField(blank=True, default=None, null=True)),
                ('ciPlayerId', models.IntegerField(blank=True, default=None, null=True)),
                ('battingTypeId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.battingtype')),
                ('bowlerTypeId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.bowlertype')),
                ('bowlingTypeId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.bowlingtype')),
                ('heightType', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.heighttype')),
                ('nationalityId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.nationality')),
            ],
        ),
    ]
