# Generated by Django 2.1.15 on 2024-02-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20240217_1411'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.IntegerField()),
                ('ballOver', models.FloatField()),
                ('innings', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('extras', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('overThrow', models.IntegerField()),
                ('ballSpeed', models.FloatField()),
                ('batSpeed', models.FloatField()),
                ('ballSpeedMetric', models.CharField(choices=[('KPH', 'KPH'), ('MPH', 'MPH')], max_length=15)),
                ('swingLength', models.FloatField()),
                ('isBoundary', models.BooleanField()),
                ('isNoBall', models.BooleanField()),
                ('isFreeHit', models.BooleanField()),
                ('shotZone', models.IntegerField()),
                ('wagonWheel', models.IntegerField()),
                ('ffData', models.IntegerField()),
                ('ballRelease', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BatSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CreaseMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DismissalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ShotConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='ball',
            name='batSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.BatSubject'),
        ),
        migrations.AddField(
            model_name='ball',
            name='batsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.Batsman'),
        ),
        migrations.AddField(
            model_name='ball',
            name='battingTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_battingTeam', to='match.Team'),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowler', to='player.Player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowlingTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowlingTeam', to='match.Team'),
        ),
        migrations.AddField(
            model_name='ball',
            name='creaseMovement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.CreaseMovement'),
        ),
        migrations.AddField(
            model_name='ball',
            name='deliveryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.DeliveryType'),
        ),
        migrations.AddField(
            model_name='ball',
            name='fielder1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_fielder1', to='player.Player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='fielder2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_fielder2', to='player.Player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='fielding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.Fielding'),
        ),
        migrations.AddField(
            model_name='ball',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.Keeper'),
        ),
        migrations.AddField(
            model_name='ball',
            name='matchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match'),
        ),
        migrations.AddField(
            model_name='ball',
            name='nonStriker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_nonStriker', to='player.Player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='shotConnection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.ShotConnection'),
        ),
        migrations.AddField(
            model_name='ball',
            name='striker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_striker', to='player.Player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='stroke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.Stroke'),
        ),
        migrations.AddField(
            model_name='ball',
            name='umpire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ball.Umpire'),
        ),
    ]
