# Generated by Django 4.1.1 on 2023-11-05 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('displayName', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('matchCount', models.IntegerField()),
                ('isWarmUp', models.BooleanField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third gender', 'Third gender')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('players', models.ManyToManyField(related_name='teams', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('over', models.CharField(choices=[('Limited', 'Limited'), ('Un-Limited', 'Un-Limited')], max_length=15)),
                ('numberOfOvers', models.IntegerField()),
                ('inningsCount', models.IntegerField()),
                ('dayOrNight', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('DayNight', 'DayNight')], max_length=15)),
                ('knockout', models.CharField(choices=[('League', 'League'), ('Quarter Final', 'Quarter Final'), ('Semi Final', 'Semi Final'), ('Final', 'Final'), ('Others', 'Others'), ('Qualifier', 'Qualifier'), ('Eliminator', 'Eliminator'), ('Super Four', 'Super Four'), ('Third Place', 'Third Place')], max_length=25)),
                ('option', models.CharField(choices=[('Batting', 'Batting'), ('Fielding', 'Fielding')], max_length=15)),
                ('first', models.CharField(choices=[('Day', 'Day'), ('Under Lights', 'Under Lights')], max_length=15)),
                ('second', models.CharField(choices=[('Day', 'Day'), ('Under Lights', 'Under Lights')], max_length=25)),
                ('captainA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_captainA', to='player.player')),
                ('captainB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_captainB', to='player.player')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.competition')),
                ('playingA', models.ManyToManyField(related_name='matches_playingA', to='player.player')),
                ('playingB', models.ManyToManyField(related_name='matches_playingB', to='player.player')),
                ('squadA', models.ManyToManyField(related_name='matches_squadA', to='player.player')),
                ('squadB', models.ManyToManyField(related_name='matches_squadB', to='player.player')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.stadium')),
                ('teamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamA', to='match.team')),
                ('teamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_teamB', to='match.team')),
                ('tossWonBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_toss_won_by', to='match.team')),
                ('wicketKeeperA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_wicket_keeperA', to='player.player')),
                ('wicketKeeperB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_wicket_keeperB', to='player.player')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='matchType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matchtype'),
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(to='match.team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.tournament'),
        ),
    ]
